#!/usr/bin/env python3
"""Builds migrations/0003_seed_launch.sql from web/landing/content/promos.json.
Curated launch creators are owned by placeholder founder accounts (founder+<handle>@promovote.com);
the founder can take them over later by changing the email in the admin tools.
Ids are deterministic (uuid5) so the file is stable when regenerated."""
import json, uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
data = json.loads((ROOT / "web/landing/content/promos.json").read_text())
NS = uuid.UUID("6f1c2b0e-5d1a-4c7e-9a43-70726f6d6f76")
uid = lambda *parts: str(uuid.uuid5(NS, "/".join(parts)))
q = lambda v: "null" if v is None else "'" + str(v).replace("'", "''") + "'"
j = lambda v: q(json.dumps(v, ensure_ascii=False, separators=(",", ":")))
SITE = "https://promovote.com"
NOW = "2026-10-06T00:00:00.000Z"
KIND = {"games": "game_dev", "apps": "app_maker", "shops": "shop"}
CTA = {"appstore": "app_store", "shop": "shop", None: "etsy"}
PLATFORM = {"apps.apple.com": "app_store", "etsy.com": "etsy"}

out = ["-- Generated by scripts/gen-seed-sql.py from web/landing/content/promos.json. Do not edit by hand."]
for handle, c in data["creators"].items():
    user_id, prof_id = uid("user", handle), uid("profile", handle)
    out.append(f"insert into \"user\" (id, name, email, emailVerified, createdAt, updatedAt) values ({q(user_id)}, {q(c['name'])}, {q('founder+' + handle + '@promovote.com')}, 1, {q(NOW)}, {q(NOW)});")
    out.append(f"insert into account_private (user_id, account_type, birth_year, age_confirmed_at, country_code, terms_accepted_at, terms_version) values ({q(user_id)}, 'creator', 1990, {q(NOW)}, 'US', {q(NOW)}, '2026-10-02');")
    avatar = c["avatar"].get("img")
    out.append(
        f"insert into profiles (id, owner_user_id, type, handle, display_name, bio, i18n, avatar_url, banner_url, is_verified, verified_at) values "
        f"({q(prof_id)}, {q(user_id)}, 'creator', {q(handle)}, {q(c['name'])}, {q(c['bio']['en'])}, {j({'bio': c['bio'], 'kind': c['kind'], 'mono': c['avatar'].get('mono')})}, "
        f"{q(SITE + avatar if avatar else None)}, {q(SITE + '/media/' + c['banner'])}, 1, {q(NOW)});"
    )
    out.append(f"insert into profile_settings (profile_id) values ({q(prof_id)});")
    cta = c.get("cta", {})
    out.append(
        f"insert into creator_details (profile_id, kind, category, founding_creator, founder_owned, release_status, android_status, ios_status) values "
        f"({q(prof_id)}, {q(KIND[c['category']])}, {q(c['category'])}, 1, 1, {q('soon' if c.get('status') == 'soon' else 'live')}, "
        f"{q(cta.get('android'))}, {q('live' if cta.get('type') == 'store' else None)});"
    )
    if c.get("link"):
        url = c["link"]["url"]
        plat = next((v for k, v in PLATFORM.items() if k in url), "website")
        out.append(f"insert into profile_links (id, profile_id, platform, url_input, canonical_url, label, verify_status, safety_status, verified_at, last_scanned_at) values ({q(uid('link', handle))}, {q(prof_id)}, {q(plat)}, {q(url)}, {q(url)}, {q(c['link']['label'])}, 'verified', 'safe', {q(NOW)}, {q(NOW)});")

tags = {}
for i, p in enumerate(data["promos"]):
    c = data["creators"][p["creator"]]
    pid, prof_id = uid("promo", p["id"]), uid("profile", p["creator"])
    cta_kind = CTA.get(p.get("linkKind")) if p.get("link") else ("notify" if c.get("cta", {}).get("type") == "notify" else None)
    live_at = f"2026-10-0{2 + i % 4}T12:{i:02d}:00.000Z"
    out.append(
        f"insert into promos (id, creator_profile_id, slug, lang, title, description, i18n, status, cta_kind, cta_url, cta_safety_status, has_perk, rights_confirmed_at, submitted_at, approved_at, live_at) values "
        f"({q(pid)}, {q(prof_id)}, {q(p['id'])}, {q(p['lang'])}, {q(p['title']['en'][:60])}, {q(p['desc']['en'][:280])}, {j({'title': p['title'], 'desc': p['desc']})}, 'live', "
        f"{q(cta_kind)}, {q(p.get('link'))}, {q('safe' if p.get('link') else 'pending')}, {1 if c.get('perk') else 0}, {q(NOW)}, {q(NOW)}, {q(NOW)}, {q(live_at)});"
    )
    v = p["video"]
    out.append(
        f"insert into promo_videos (id, promo_id, label, mp4_url, webm_url, poster_url, duration_ms, width, height) values "
        f"({q(uid('video', p['id']))}, {q(pid)}, 'A', {q(f'{SITE}/media/{v}.mp4')}, {q(f'{SITE}/media/{v}.webm')}, {q(f'{SITE}/media/{v}-poster.jpg')}, {p['dur'] * 1000}, 720, 1280);"
    )
    for pos, tag in enumerate(p.get("tags", [])):
        tags[tag] = tags.get(tag, 0) + 1
        out.append(f"insert into promo_hashtags (promo_id, tag, position) values ({q(pid)}, {q(tag)}, {pos});")

out.insert(1, "insert into hashtags (tag, use_count) values " + ", ".join(f"({q(t)}, {n})" for t, n in sorted(tags.items())) + ";")
(Path(__file__).resolve().parents[1] / "migrations/0003_seed_launch.sql").write_text("\n".join(out) + "\n")
print(f"seed: {len(data['creators'])} creators, {len(data['promos'])} promos, {len(tags)} hashtags")
